[package]
name = "thorsen-pm"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
dotenv = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tera = "1.19.1"
